package main

import (
	"regexp"
	"sort"
	"strings"
	"unicode"

	jen "github.com/dave/jennifer/jen"
)

var nonAlnum = regexp.MustCompile(`[^a-zA-Z0-9]+`)

// sortItems sorts a slice of items alphabetically by name.
func sortItems(items []Item) {
	sort.Slice(items, func(i, j int) bool {
		return items[i].Name < items[j].Name
	})
}

// toGoIdentifier converts an arbitrary name into a valid exported Go identifier.
func toGoIdentifier(name string) string {
	parts := nonAlnum.Split(name, -1)
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		runes := []rune(p)
		runes[0] = unicode.ToUpper(runes[0])
		b.WriteString(string(runes))
	}
	id := b.String()
	if id == "" {
		return "Unknown"
	}
	if unicode.IsDigit(rune(id[0])) {
		id = "N" + id
	}
	return id
}

// generate writes a Go test file to outputPath for the given collection.
func generate(collection Collection, outputPath, pkgName, suiteName string) error {
	f := jen.NewFile(pkgName)
	f.HeaderComment("Code generated by gopostman. DO NOT EDIT.")

	sortItems(collection.Item)
	generateItems(f, collection.Item, "", suiteName)

	return f.Save(outputPath)
}

// generateItems recursively walks folders and emits a test method for each request.
func generateItems(f *jen.File, items []Item, prefix, suiteName string) {
	for _, item := range items {
		if item.Request != nil {
			generateTestMethod(f, item, prefix, suiteName)
		} else {
			// folder
			sortItems(item.Item)
			folderID := toGoIdentifier(item.Name)
			child := folderID
			if prefix != "" {
				child = prefix + "_" + folderID
			}
			generateItems(f, item.Item, child, suiteName)
		}
	}
}

// generateTestMethod emits a single test method on the suite for one Postman request.
func generateTestMethod(f *jen.File, item Item, prefix, suiteName string) {
	req := item.Request
	if req == nil {
		return
	}

	// Build method name: Test<Folder_…><RequestName>
	methodName := "Test"
	if prefix != "" {
		methodName += prefix + "_"
	}
	methodName += toGoIdentifier(item.Name)

	method := strings.ToUpper(req.Method)
	rawURL := req.URL.Raw

	var stmts []jen.Code

	// --- build body expression ---
	needsStrings := false
	var bodyExpr jen.Code
	if req.Body != nil && req.Body.Mode == "raw" && req.Body.Raw != "" {
		needsStrings = true
		bodyExpr = jen.Qual("strings", "NewReader").Call(jen.Lit(req.Body.Raw))
	} else {
		bodyExpr = jen.Nil()
	}
	_ = needsStrings // jen handles imports via Qual

	// req, err := http.NewRequest("METHOD", "URL", body)
	stmts = append(stmts,
		jen.List(jen.Id("req"), jen.Id("err")).Op(":=").
			Qual("net/http", "NewRequest").Call(
				jen.Lit(method),
				jen.Lit(rawURL),
				bodyExpr,
			),
		jen.Id("s").Dot("Require").Call().Dot("NoError").Call(jen.Id("err")),
	)

	// Authorization: Bearer + s.token
	stmts = append(stmts,
		jen.Id("req").Dot("Header").Dot("Set").Call(
			jen.Lit("Authorization"),
			jen.Lit("Bearer ").Op("+").Id("s").Dot("token"),
		),
	)

	// Custom headers from the Postman request (skip disabled and Authorization)
	for _, h := range req.Header {
		if h.Disabled {
			continue
		}
		if strings.EqualFold(h.Key, "Authorization") {
			continue
		}
		stmts = append(stmts,
			jen.Id("req").Dot("Header").Dot("Set").Call(
				jen.Lit(h.Key),
				jen.Lit(h.Value),
			),
		)
	}

	// resp, err := http.DefaultClient.Do(req)
	stmts = append(stmts,
		jen.List(jen.Id("resp"), jen.Id("err")).Op(":=").
			Qual("net/http", "DefaultClient").Dot("Do").Call(jen.Id("req")),
		jen.Id("s").Dot("Require").Call().Dot("NoError").Call(jen.Id("err")),
		jen.Defer().Id("resp").Dot("Body").Dot("Close").Call(),
		jen.Id("s").Dot("Equal").Call(
			jen.Qual("net/http", "StatusOK"),
			jen.Id("resp").Dot("StatusCode"),
		),
	)

	f.Line()
	f.Func().
		Params(jen.Id("s").Op("*").Id(suiteName)).
		Id(methodName).
		Params().
		Block(stmts...)
}
